### ISSUE TITLE
Panic: division by zero. There is something wrong when running the script.

### ISSUE THREAD

**Issue by HtcOrange** [kubernetes/perf-tests#1104]
The testing went wrong!  The results are as following:
```bash
./clusterloader --kubeconfig=/home/archlab/.kube/config --masterip=192.168.10.135 --mastername=archlab --testconfig=testing/density/config.yaml --report-dir=./reports --alsologtostderr 2>&1 | tee ./logs/tmp.log
I0304 18:35:38.718173   21136 clusterloader.go:117] ClusterConfig.Nodes set to 2
E0304 18:35:38.719313   21136 clusterloader.go:143] Getting master internal ip error: didn't find any InternalIP master IPs
I0304 18:35:38.719509   21136 clusterloader.go:218] Using config: {ClusterConfig:{KubeConfigPath:/home/archlab/.kube/config Nodes:2 Provider: EtcdInsecurePort:2382 MasterIPs:[192.168.10.135] MasterInternalIPs:[] MasterName:archlab KubemarkRootKubeConfigPath: DeleteStaleNamespaces:false} ReportDir:./reports EnableExecService:false TestScenario:{Identifier: ConfigPath: OverridePaths:[]} PrometheusConfig:{EnableServer:false TearDownServer:true ScrapeEtcd:false ScrapeNodeExporter:false ScrapeKubelets:false ScrapeKubeProxy:true}}
I0304 18:35:38.720727   21136 cluster.go:56] Listing cluster nodes:
I0304 18:35:38.720743   21136 cluster.go:68] Name: gg-133, clusterIP: 192.168.10.133, externalIP: , isSchedulable: true
I0304 18:35:38.720749   21136 cluster.go:68] Name: gg-134, clusterIP: 192.168.10.134, externalIP: , isSchedulable: true
I0304 18:35:38.720754   21136 cluster.go:68] Name: gg-135, clusterIP: 192.168.10.135, externalIP: , isSchedulable: false
W0304 18:35:38.723256   21136 imagepreload.go:85] No images specified. Skipping image preloading
I0304 18:35:38.723264   21136 clusterloader.go:179] --------------------------------------------------------------------------------
I0304 18:35:38.723267   21136 clusterloader.go:180] Running testing/density/config.yaml
I0304 18:35:38.723270   21136 clusterloader.go:181] --------------------------------------------------------------------------------
panic: division by zero [recovered]
        panic: division by zero

goroutine 1 [running]:
text/template.errRecover(0xc420357838)
        /usr/local/go/src/text/template/exec.go:143 +0x1ba
panic(0x12dca60, 0x163a980)
        /usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/perf-tests/clusterloader2/pkg/config.divideFloat(0x12d8460, 0xc42027f278, 0x12d8460, 0xc4203104d0, 0x412e3c)
        /home/archlab/gocode/src/k8s.io/perf-tests/clusterloader2/pkg/config/template_functions.go:160 +0xa4
k8s.io/perf-tests/clusterloader2/pkg/config.divideInt(0x12d8460, 0xc42027f278, 0x12d8460, 0xc4203104d0, 0x0)
        /home/archlab/gocode/src/k8s.io/perf-tests/clusterloader2/pkg/config/template_functions.go:131 +0x49
reflect.Value.call(0x131b9e0, 0x15b57a0, 0x13, 0x151ca7e, 0x4, 0xc4203105a0, 0x2, 0x2, 0x1519be0, 0x1, ...)
        /usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x131b9e0, 0x15b57a0, 0x13, 0xc4203105a0, 0x2, 0x2, 0x1661820, 0xc4205fcf30, 0x12d8460)
        /usr/local/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc4203577b8, 0x13440c0, 0xc420258510, 0x15, 0x131b9e0, 0x15b57a0, 0x13, 0x16614e0, 0xc4205fce10, 0xc4205e35e6, ...)
        /usr/local/go/src/text/template/exec.go:667 +0x4f1
text/template.(*state).evalFunction(0xc4203577b8, 0x13440c0, 0xc420258510, 0x15, 0xc4205fce40, 0x16614e0, 0xc4205fce10, 0xc42009f6c0, 0x3, 0x4, ...)
        /usr/local/go/src/text/template/exec.go:535 +0x176
text/template.(*state).evalCommand(0xc4203577b8, 0x13440c0, 0xc420258510, 0x15, 0xc4205fce10, 0x0, 0x0, 0x0, 0x12d8460, 0xc42027f098, ...)
        /usr/local/go/src/text/template/exec.go:432 +0x516
text/template.(*state).evalPipeline(0xc4203577b8, 0x13440c0, 0xc420258510, 0x15, 0xc4200d5e00, 0x0, 0x0, 0x82)
        /usr/local/go/src/text/template/exec.go:405 +0x10f
text/template.(*state).walk(0xc4203577b8, 0x13440c0, 0xc420258510, 0x15, 0x16613e0, 0xc4205fcf60)
        /usr/local/go/src/text/template/exec.go:231 +0x4a5
text/template.(*state).walk(0xc4203577b8, 0x13440c0, 0xc420258510, 0x15, 0x1661620, 0xc420258d50)
        /usr/local/go/src/text/template/exec.go:239 +0x11d
text/template.(*Template).execute(0xc42009f080, 0x163f4c0, 0xc4203f4100, 0x13440c0, 0xc420258510, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:194 +0x1e6
text/template.(*Template).Execute(0xc42009f080, 0x163f4c0, 0xc4203f4100, 0x13440c0, 0xc420258510, 0x1000, 0x14a8100)
        /usr/local/go/src/text/template/exec.go:177 +0x53
k8s.io/perf-tests/clusterloader2/pkg/config.(*TemplateProvider).getMappedTemplate(0xc4200d5720, 0x7fff934be54e, 0xb, 0xc420258510, 0xc4202588d0, 0xc420258840, 0xc4202587b0, 0xc420258720, 0xc420258690)
        /home/archlab/gocode/src/k8s.io/perf-tests/clusterloader2/pkg/config/template_provider.go:129 +0x17c
k8s.io/perf-tests/clusterloader2/pkg/config.(*TemplateProvider).TemplateToConfig(0xc4200d5720, 0x7fff934be54e, 0xb, 0xc420258510, 0xc420258510, 0x166d640, 0xc4200e33e0)
        /home/archlab/gocode/src/k8s.io/perf-tests/clusterloader2/pkg/config/template_provider.go:152 +0x4d
k8s.io/perf-tests/clusterloader2/pkg/test.RunTest(0xc4202ad980, 0x0, 0x1fb43e0, 0x1b)
        /home/archlab/gocode/src/k8s.io/perf-tests/clusterloader2/pkg/test/test.go:60 +0x229
main.runSingleTest(0xc4202ad980, 0x0, 0xc420357ef0, 0xc42013f810)
        /home/archlab/gocode/src/k8s.io/perf-tests/clusterloader2/cmd/clusterloader.go:315 +0x17a
main.main()
        /home/archlab/gocode/src/k8s.io/perf-tests/clusterloader2/cmd/clusterloader.go:282 +0x921
```
Why is that? Does the key point come from the risk of dividing by zero? I am very anxious to enlist your help!

**Comment by mm4tt** [comment]
Yeah, sorry about that. This is a known issue - https://github.com/kubernetes/perf-tests/issues/887
Density and Load tests were designed to work with clusters with at least 100 nodes (it's where the scale begins for us). As of now, it's now possible to run them for smaller clusters (without some manual edits).

/close
