### ISSUE TITLE
Potential segfault in runtimeobjects.GetNumObjectsMatchingSelector method

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1248]
It happened in one of our 1.16 tests, but the vulnerability is present in all release branches.

Stacktrace:
```
W0513 00:57:50.893] panic: runtime error: invalid memory address or nil pointer dereference
W0513 00:57:50.893] [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11bd734]
W0513 00:57:50.893] 
W0513 00:57:50.893] goroutine 672187 [running]:
W0513 00:57:50.893] k8s.io/perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects.GetNumObjectsMatchingSelector.func1(0xc021068bc0, 0x15)
W0513 00:57:50.894] 	/go/src/k8s.io/perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go:409 +0x1d4
W0513 00:57:50.894] k8s.io/perf-tests/clusterloader2/pkg/framework/client.RetryFunction.func1(0x14f6fe0, 0x1674701, 0x0)
W0513 00:57:50.894] 	/go/src/k8s.io/perf-tests/clusterloader2/pkg/framework/client/objects.go:113 +0x32
W0513 00:57:50.894] k8s.io/perf-tests/clusterloader2/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x5f5e100, 0x4008000000000000, 0x0, 0x6, 0x0, 0xc081ec9180, 0x0, 0x0)
W0513 00:57:50.894] 	/go/src/k8s.io/perf-tests/clusterloader2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:284 +0x51
W0513 00:57:50.894] k8s.io/perf-tests/clusterloader2/pkg/framework/client.RetryWithExponentialBackOff(...)
W0513 00:57:50.895] 	/go/src/k8s.io/perf-tests/clusterloader2/pkg/framework/client/objects.go:59
W0513 00:57:50.895] k8s.io/perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects.GetNumObjectsMatchingSelector(0x17af880, 0xc00ab37a80, 0xc05db3d950, 0xe, 0x0, 0x0, 0xc0527bf880, 0x2, 0xc021068c00, 0x16, ...)
W0513 00:57:50.895] 	/go/src/k8s.io/perf-tests/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go:412 +0x147
W0513 00:57:50.895] k8s.io/perf-tests/clusterloader2/pkg/test.getReplicaCountOfNewObject(0x1800bc0, 0xc00c18c960, 0xc05db3d950, 0xe, 0xc001535140, 0xc021068a20, 0x15, 0x0)
W0513 00:57:50.895] 	/go/src/k8s.io/perf-tests/clusterloader2/pkg/test/simple_test_executor.go:378 +0x274
W0513 00:57:50.895] k8s.io/perf-tests/clusterloader2/pkg/test.(*simpleTestExecutor).ExecutePhase(0x23909c8, 0x1800bc0, 0xc00c18c960, 0xc00fbdc7f8, 0x0)
W0513 00:57:50.896] 	/go/src/k8s.io/perf-tests/clusterloader2/pkg/test/simple_test_executor.go:172 +0x541
W0513 00:57:50.896] k8s.io/perf-tests/clusterloader2/pkg/test.(*simpleTestExecutor).ExecuteStep.func2()
W0513 00:57:50.896] 	/go/src/k8s.io/perf-tests/clusterloader2/pkg/test/simple_test_executor.go:133 +0x4e
W0513 00:57:50.896] k8s.io/perf-tests/clusterloader2/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc05c835600, 0xc06607db30)
W0513 00:57:50.896] 	/go/src/k8s.io/perf-tests/clusterloader2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
W0513 00:57:50.896] created by k8s.io/perf-tests/clusterloader2/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
W0513 00:57:50.896] 	/go/src/k8s.io/perf-tests/clusterloader2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by mm4tt** [comment]
Sent https://github.com/kubernetes/perf-tests/pull/1249, once it gets in I'll cherypick it into older releases
