### ISSUE TITLE
nodelocaldns perf tests failing after migration to python3

### ISSUE THREAD

**Issue by prameshj** [kubernetes/perf-tests#1586]
**Which jobs are failing**: 
NodelocalDNS benchmark/scale test.
Results used to be http://perf-dash.k8s.io/#/?jobname=node-local-dns%20benchmark&metriccategoryname=dns&metricname=Queries, but this is empty since tests arent running.

**Which test(s) are failing**: nodelocaldns scale test, no periodic CI

**Since when has it been failing**:
Since https://github.com/kubernetes/perf-tests/pull/1470 merged

**Testgrid link**:
No periodic OSS tests are being run

**Reason for failure**:
most likely due to migrating to python3, it worked fine when using python2.
```
W1119 01:09:33.272] 2020/11/19 01:09:33 process.go:153: Running: /go/src/k8s.io/perf-tests/run-e2e.sh node-local-dns /workspace/_artifacts/out /workspace/_artifacts
I1119 01:09:34.084] Collecting numpy
I1119 01:09:34.151]   Downloading numpy-1.19.4-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
I1119 01:09:34.862] Installing collected packages: numpy
I1119 01:09:36.211] Successfully installed numpy-1.19.4
W1119 01:09:36.728] INFO 11-19 01:09:36 runner.py:81] Using existing node-local-dns for tests
W1119 01:09:36.729] INFO 11-19 01:09:36 runner.py:86] DNS service IP is 169.254.20.10
W1119 01:09:37.572] INFO 11-19 01:09:37 runner.py:470] Created rundir /workspace/_artifacts/out/run-1605748177
W1119 01:09:37.572] INFO 11-19 01:09:37 runner.py:476] Updated symlink /workspace/_artifacts/out/latest
W1119 01:09:37.573] INFO 11-19 01:09:37 runner.py:416] Starting client teardown
W1119 01:09:37.819] INFO 11-19 01:09:37 runner.py:426] Client teardown complete
W1119 01:09:37.823] INFO 11-19 01:09:37 runner.py:340] Starting server teardown
W1119 01:09:38.369] INFO 11-19 01:09:38 runner.py:439] Waiting for server to be deleted (0 pods active)
W1119 01:09:38.369] INFO 11-19 01:09:38 runner.py:348] Server teardown ok
W1119 01:09:38.444] INFO 11-19 01:09:38 runner.py:416] Starting client teardown
W1119 01:09:38.729] INFO 11-19 01:09:38 runner.py:426] Client teardown complete
W1119 01:09:38.730] Traceback (most recent call last):
W1119 01:09:38.730]   File "py/run_perf.py", line 119, in <module>
W1119 01:09:38.730]     sys.exit(runner.go())
W1119 01:09:38.730]   File "/go/src/k8s.io/perf-tests/dns/py/runner.py", line 101, in go
W1119 01:09:38.730]     client_pods=self._reset_client()
W1119 01:09:38.730]   File "/go/src/k8s.io/perf-tests/dns/py/runner.py", line 360, in _reset_client
W1119 01:09:38.730]     self._create(self.dnsperf_yaml)
W1119 01:09:38.730]   File "/go/src/k8s.io/perf-tests/dns/py/runner.py", line 178, in _create
W1119 01:09:38.731]     ret, out, err = self._kubectl(yaml.dump(yaml_obj), 'create', '-f', '-')
W1119 01:09:38.731]   File "/go/src/k8s.io/perf-tests/dns/py/runner.py", line 165, in _kubectl
W1119 01:09:38.731]     _log.debug('kubectl stdin\n%s', add_prefix('in  | ', stdin))
W1119 01:09:38.731]   File "/go/src/k8s.io/perf-tests/dns/py/runner.py", line 44, in add_prefix
W1119 01:09:38.731]     return '\n'.join([prefix + l for l in text.decode().split('\n')])
W1119 01:09:38.731] AttributeError: 'str' object has no attribute 'decode'
W1119 01:09:40.458] 2020/11/19 01:09:40 process.go:155: Step '/go/src/k8s.io/perf-tests/run-e2e.sh node-local-dns /workspace/_artifacts/out /workspace/_artifacts' finished in 7.290153211s
W1119 01:09:40.458] 2020/11/19 01:09:40 process.go:153: Running: gcloud compute firewall-rules describe e2e-ports-0864fe2a --project=gke-scalability-5 --format=value(name)
W1119 01:09:41.268] 2020/11/19 01:09:41 process.go:155: Step 'gcloud compute firewall-rules describe e2e-ports-0864fe2a --project=gke-scalability-5 --format=value(name)' finished in 810.288006ms
W1119 01:09:41.269] 2020/11/19 01:09:41 process.go:153: Running: bash -c 
```

**Anything else we need to know**:

**Comment by mm4tt** [comment]
/cc

Hey Pavithra, thanks for catching this. I'll see into getting this fixed next week.

**Comment by mm4tt** [comment]
There are actually two issues here

1. Prow job succeeding even though the python code fails
2. Python code fails as a result of python2-> python3 migration

Let me tackle the 1. first. Once we have working continuous and presubmit tests it will be easier to fix 2.

**Comment by mm4tt** [comment]
The culprit of 1 is that exit status is not properly propagated:
```
./run-e2e.sh node-local-dns    
TOOL_NAME: node-local-dns
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.19.4)
You are using pip version 18.1, however version 20.3b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "py/run_perf.py", line 23, in <module>
    from runner import Runner
  File "/Users/mmatejczyk/go/src/k8s.io/perf-tests/dns/py/runner.py", line 23, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
➜  perf-tests git:(dns_exit_status) echo $?                        
0
```

**Comment by mm4tt** [comment]
The issue no. 1 has been fixed in https://github.com/kubernetes/perf-tests/pull/1588.

Fixing issue no. 2 in https://github.com/kubernetes/perf-tests/pull/1587

**Comment by mm4tt** [comment]
The test seems to be genuinely passing now - https://k8s-testgrid.appspot.com/sig-scalability-benchmarks#kube-dns&grid=old
/close
