### ISSUE TITLE
DNS perf crashing on simple test

### ISSUE THREAD

**Issue by jonaskint** [kubernetes/perf-tests#39]
Hi, I'm currently trying to benchmark our internal kubernetes dns with the perf tool and play with the dnsmasq settings. A simple run crashes instantaneously and I'm not sure if it's me that misread the docutmentation or if it's a bug. Here is a sample of the output:

```
❯ ./run --params params/default.yaml --use-cluster-dns --out-dir out
INFO 04-07 12:39:49 runner.py:60] Using cluster DNS for tests
INFO 04-07 12:39:49 runner.py:64] DNS service IP is 10.0.0.10
INFO 04-07 12:39:50 runner.py:217] Client node is ip-10-2-11-248.eu-central-1.compute.internal
INFO 04-07 12:39:50 runner.py:331] Created rundir out/run-1491561590
INFO 04-07 12:39:50 runner.py:337] Updated symlink out/latest
INFO 04-07 12:39:50 runner.py:277] Starting client teardown
INFO 04-07 12:39:50 runner.py:287] Client teardown complete
INFO 04-07 12:39:50 runner.py:140] Create Pod/kube-dns-perf-client ok
INFO 04-07 12:39:51 runner.py:254] Client pod to started on ip-10-2-11-248.eu-central-1.compute.internal
INFO 04-07 12:39:53 runner.py:262] Client pod ready for execution
INFO 04-07 12:39:53 runner.py:266] Copying query files to client
INFO 04-07 12:39:53 runner.py:233] Starting server teardown
INFO 04-07 12:39:54 runner.py:300] Waiting for server to be deleted (0 pods active)
INFO 04-07 12:39:54 runner.py:240] Server teardown ok
INFO 04-07 12:39:54 runner.py:277] Starting client teardown
INFO 04-07 12:39:55 runner.py:285] Waiting for client pod to terminate
INFO 04-07 12:39:56 runner.py:285] Waiting for client pod to terminate
INFO 04-07 12:39:58 runner.py:285] Waiting for client pod to terminate
INFO 04-07 12:39:59 runner.py:285] Waiting for client pod to terminate
INFO 04-07 12:39:59 runner.py:287] Client teardown complete
Traceback (most recent call last):
  File "py/run_perf.py", line 87, in <module>
    sys.exit(runner.go())
  File "/Users/jonas/Github/perf-tests/dns/py/runner.py", line 79, in go
    self._reset_client()
  File "/Users/jonas/Github/perf-tests/dns/py/runner.py", line 263, in _reset_client
    self._copy_query_files()
  File "/Users/jonas/Github/perf-tests/dns/py/runner.py", line 268, in _copy_query_files
    ['/bin/tar', '-czf', '-', self.args.query_dir])
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I see the `kube-dns-perf-client` pod spinning up but it shuts down after 2 seconds.

**Comment by bowei** [comment]
let me take a look

**Comment by jtuthehien** [comment]
You are probably running on OSX which doesnt have bin/tar by default
