### ISSUE TITLE
exec `./run core-dns out ` got `error gettings dns ip for service kube-dns`

### ISSUE THREAD

**Issue by xieyanker** [kubernetes/perf-tests#864]
Hello, I clone the newest code, and I exec `./run core-dns out` got `error gettings dns ip for service kube-dns`
```shell
root@master1:~/xujingsong/perf-tests/dns# ./run core-dns out
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages
INFO 10-22 10:56:04 runner.py:77] Using cluster DNS for tests
Traceback (most recent call last):
  File "py/run_perf.py", line 118, in <module>
    runner = Runner(args)
  File "/root/xujingsong/perf-tests/dns/py/runner.py", line 78, in __init__
    self.args.dns_ip = self._get_dns_ip("kube-dns")
  File "/root/xujingsong/perf-tests/dns/py/runner.py", line 335, in _get_dns_ip
    raise Exception('error gettings dns ip for service %s: %d' %(svcname, code))
Exception: error gettings dns ip for service kube-dns: 1

```

**Comment by xieyanker** [comment]
However, it seems success run when I exec `python py/run_perf.py --dns-server coredns --params params/coredns/default.yaml --out-dir out`, so I commit a PR #865
